### ISSUE TITLE
cannot obtain TXT record 

### ISSUE THREAD

**Issue by bsdmad** [bluemonk/net-dns#22]
With net/dns ver. 6.1, I cannot obtain TXT record, for example, for google.com.

[ueda@bpr Test]$ irb -r rubygems -r net/dns/resolver
irb(main):001:0> p Net::DNS::Resolver.start("google.com", Net::DNS::TXT)
;; Answer received from XXX.XXX.XXX.XXX:53 (258 bytes)
;;
;; HEADER SECTION
;; id = 54041
;; qr = 1       opCode: QUERY   aa = 0  tc = 0  rd = 1
;; ra = 1       ad = 0  cd = 0  rcode = NoError
;; qdCount = 1  anCount = 1     nsCount = 4     arCount = 4

;; QUESTION SECTION (1 record):
;; google.com.                  IN      TXT

;; ANSWER SECTION (1 record):
google.com.             3600    IN      TXT

;; AUTHORITY SECTION (4 records):
google.com.             63829   IN      NS      ns2.google.com.
google.com.             63829   IN      NS      ns4.google.com.
google.com.             63829   IN      NS      ns3.google.com.
google.com.             63829   IN      NS      ns1.google.com.

;; ADDITIONAL SECTION (4 records):
ns1.google.com.         63367   IN      A       216.239.32.10
ns2.google.com.         63367   IN      A       216.239.34.10
ns3.google.com.         63368   IN      A       216.239.36.10
ns4.google.com.         63367   IN      A       216.239.38.10

=> nil

of course, I can obtain it with dig command:

[ueda@bpr Test]$ dig TXT google.com @XXX.XXX.XXX.XXX

; <<>> DiG 9.2.4 <<>> TXT google.com @nsc2.netforest.ad.jp
; (1 server found)
;; global options:  printcmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19579
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 4

;; QUESTION SECTION:
;google.com.                    IN      TXT

;; ANSWER SECTION:
google.com.             3476    IN      TXT     "v=spf1 include:_netblocks.google.com ip4:216.73.93.70/31 ip4:216.73.93.72/31 ~all"

;; AUTHORITY SECTION:
google.com.             63705   IN      NS      ns2.google.com.
google.com.             63705   IN      NS      ns1.google.com.
google.com.             63705   IN      NS      ns3.google.com.
google.com.             63705   IN      NS      ns4.google.com.

;; ADDITIONAL SECTION:
ns1.google.com.         63243   IN      A       216.239.32.10
ns2.google.com.         63243   IN      A       216.239.34.10
ns3.google.com.         63244   IN      A       216.239.36.10
ns4.google.com.         63243   IN      A       216.239.38.10

;; Query time: 2 msec
;; SERVER: 218.45.29.108#53(218.45.29.108)
;; WHEN: Sat Jun 11 17:39:34 2011
;; MSG SIZE  rcvd: 258

**Comment by Supermathie** [comment]
This behaviour has regressed:

```
[16] pry(main)> puts Net::DNS::Resolver.start("google.com", Net::DNS::TXT).answer;
W, [2019-10-21T10:44:14.366030 #17692]  WARN -- : Packet truncated, retrying using TCP
google.com.             22      IN      TXT     
google.com.             22      IN      TXT     
google.com.             22      IN      TXT     
google.com.             22      IN      TXT     
google.com.             22      IN      TXT     
```

Tested with:
* gem version 0.9.0 and both ruby 2.3.3p222 and 2.6.2p47
* gem version 0.8.0, 0.7.1, 0.7.0 and ruby 2.6.2p47
