### ISSUE TITLE
ArgumentError - comparison of Fixnum with nil failed

### ISSUE THREAD

**Issue by eLod** [bluemonk/net-dns#48]
I believe this is caused by a misbehaving DNS server, i can't reproduce the error, but it happens occasionally. The log shows the error is at https://github.com/bluemonk/net-dns/blob/master/lib/net/dns/resolver.rb#L1174. I think the server replies an empty string (or drops the connection, not sure), thus length (`ans.unpack("n")[0]`) becomes `nil`.

**Comment by weppos** [comment]
Can't reproduce.
