### ISSUE TITLE
pNet-DNS, Update vs net-dns

### ISSUE THREAD

**Issue by mcr** [bluemonk/net-dns#80]
My impression is that the package "pNet-DNS" is an old name for this package.  There is a fair bit of resemblance, but clealry net-dns has evolved in the past ten years.
The pNet-DNS package include DNS Update functionality, while AFAIK net-dns does not.
Am I correct in this assessment? I looked through the git history, and I didn't see a spot where it was removed, so I think it must have been removed beforehand, or maybe I'm wrong that they share a common history.
I'm looking for a pure ruby (vs system("nsupdate")) way to push DNS updates.

**Comment by weppos** [comment]
You will need to reach out to the pNet-DNS package owner. It's not the same package of this one.
